### PR TITLE
update to swift3

### PR DESCRIPTION
**Pull request by fadedblue**

### CODE REVIEW

**Comment by joedaniels29** [comment]
Thanks alot for this work!!  Do you know what the standard practice for migrating repos to swift 3 is?  Should swift 2.3 be a branch? I presume swift 3 should be on master?

**Comment by joedaniels29** [comment]
I'm otherwise happy to merge this and will do so after deciding on the above.  haha 
Thanks again!

**Comment by fadedblue** [comment]
As  other repos the swift 2 and 3  version each has their own branch, ex: https://github.com/MengTo/Spring, but, yes, swift 3 should be on master.

**Comment by fadedblue** [comment]
@joedaniels29  and, the WatchFaceTitle's calculation result is wrong in my project, dose it need make some modifications?

**Comment by joedaniels29** [comment]
I think start and end are currently reversed. I've not gotten a chance to look at that yet. I'd certainly be appreciative if you can fix it!

**Pull request merged**
